# .github/workflows/metrics.yml
name: Metrics
on:
  # Run automatically every day at midnight
  schedule: [{cron: "0 0 * * *"}]
  # Allows to trigger the workflow manually
  workflow_dispatch:
  # Run on pushes to main/master
  push: {branches: ["master", "main"]}

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to write the generated svg to the repository
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # This is required for the action to work
          token: ${{ secrets.METRICS_TOKEN }}

          # GENERAL OPTIONS
          #
          # The user to fetch metrics for
          user: gap-editor
          # The template to use
          template: classic
          # The base stats to display
          base: header, activity, community, repositories, metadata
          # The file name for the output SVG
          filename: github-metrics.svg
          
          # PLUGIN CONFIGURATIONS
          #
          # Repositories Plugin (as requested)
          # Shows recent repository activity
          plugin_repositories: yes
          plugin_repositories_limit: 4
          plugin_repositories_affiliations: owner # Show only repos you own

          # Reactions Plugin (as requested)
          # Shows a summary of reactions on your comments
          plugin_reactions: yes
          plugin_reactions_limit: 200 # Analyze last 200 reactions
          plugin_reactions_days: 30 # Limit analysis to last 30 days
          plugin_reactions_ignored: gap-editor # Ignore your own reactions
          plugin_reactions_display: absolute # Show absolute counts (e.g., 🚀 10)

          # Other useful plugins for a complete profile
          #
          # Isocalendar Plugin
          # Shows a contribution calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # Languages Plugin
          # Shows language distribution
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
          plugin_languages_colors: github
          plugin_languages_sections: most-used, recently-used

          # Lines of Code Plugin
          # Shows total lines of code added/removed
          plugin_lines: yes
