name: Metrics
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: gap-editor 
          token: ${{ secrets.GITHUB_TOKEN }}
          base: header, activity, community
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
     
